version: '3.6'

services:
  agent:
    build: .
    depends_on:
      - db
    entrypoint: /go/bin/mftracerd
  db:
    image: postgres:10.3
    ports:
      - 5432
    environment:
      - POSTGRES_USER=mftracer
      - POSTGRES_DB=mftracer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s